version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskmanagement
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
  spring:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taskmanagement
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  liquibase:
    image: liquibase/liquibase
    command: --changeLogFile=/db/changelog/db.changelog-master.yaml
    volumes:
      - ./path/to/your/changelog:/liquibase/changelog
    depends_on:
      - mysql
