version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskmanagement
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"

  spring:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    env_file:
      - .env

  liquibase:
    image: liquibase/liquibase
    command: --changeLogFile=/liquibase/changelog/db.changelog-master.yaml
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    depends_on:
      - mysql
